---
title: "Visualize Embeddings"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning = F)
library(tidyverse)
library(plotly)
library(glue)
library(lubridate)
library(stringr)

library(reticulate)
library(rvest)
library(tidytext)

strip_html <- function(s) {
    html_text(read_html(s))
}

theme_set(theme_minimal())

use_python('/home/corrie/anaconda3/bin/python', required = T)
```

```{r, message=F}
claim_reviews <- read_csv(here::here("data/all_claim_reviews.csv")) %>%
  select(-X1) %>%
  rename(id = `@id`,
         type = `@type`,
         html_text = text) %>%
  mutate(text = map_chr(html_text, .f=strip_html))

url_regex <- "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
claim_reviews <- claim_reviews %>%
  mutate(text = str_replace(text, url_regex, "WEBSITELINK")) 

claim_reviews %>%
  write_csv(here::here("data/clean_claimreviews.csv"))
```

```{r}
# run jupyter notebook

d <- read_csv("claims_w_emb.csv") %>%
  arrange(yearPublished)
```


```{r}
ax <- list(
  title = "",
  zeroline = FALSE,
  showline = FALSE,
  showticklabels = FALSE,
  showgrid = FALSE
)

plot_ly(data=d, x=~tfidf_embedding_0, y=~tfidf_embedding_1) %>%
  layout(title=list(text="<b>Claims over the Years</b><br>2015 to 2020",
                    x=0.1),
         annotations=list(x=c(5.5, 3, -1, -2.5, 4, -3.8, 2.5), 
                          y=c(2.2, -4.4, -4.5, 6, 5, 4.5, -2.7), 
                          text=c("<b>Georgia</b>",
                                 "<b>Belarus</b>", 
                                 "<b>Nuclear</b>", "<b>M17</b>", "<b>UK</b>", "<b>White Helmets</b>", "<b>Crimea</b>"), showarrow=F),
         shapes = list(
              list(type="circle",
                       x0=3.7, x1=5.7, y0=1.5, y1=3,  fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.15),
              list(type="circle",
                       x0=2.2, x1=3.9, y0=-4.2, y1=-3.2,  fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.15),
               list(type="circle",
                       x0=-1.2, x1=-0.7, y0=-3.7, y1=-4.2,  fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.15),
              list(type="circle",
                       x0=-2.3, x1=-1.0, y0=5.3, y1=6.8,  fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.15),
              list(type="circle",
                       x0=2.2, x1=3.5, y0=4.2, y1=6,  fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.15),
              list(type="circle",
                       x0=-2.2, x1=-4, y0=2.1, y1=4.2,  fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.15),
              list(type="circle",
                       x0=1.8, x1=2.8, y0=-2.5, y1=-1.1,  fillcolor = 'rgb(30, 100, 120)', line = list(color = 'rgb(30, 100, 120)'),
                   opacity = 0.25)
         ),
         xaxis=ax, 
         yaxis=ax) %>%
    add_trace(type="scatter",
            mode="markers",
            marker=list(
              opacity=0.8,
              color=~yearPublished,
              colorscale='YlGnBu',
              reversescale=TRUE,
              size=4,
              colorbar = list(
                title="Year Published"
              )
            ),
            text = ~glue('<b>Claim:</b>
    <br>{stringr::str_wrap(claimReviewed)}<br>
    <b>Year:</b>
    <br>{yearPublished}'),
      hoverinfo="text") 
  
```

```{r}
df_keywords <- d %>%
  mutate(month = floor_date(datePublished, unit="month")) %>%
  select(id, month, keyword_names) %>%
  mutate(keyword_names = str_replace(keyword_names, "\\[", "") %>%
           str_replace("\\]", "") %>%
           str_replace_all("\'", "") %>%
           str_trim() %>%
           str_split(", ") )  %>%
  unnest(keyword_names) 

common_keywords <- df_keywords %>%
  group_by(keyword_names) %>%
  count() %>%
  arrange(-n) %>%
  filter(n >= 100) %>%
  pull(keyword_names)
  
keyword_cts <-  df_keywords %>%
  filter(keyword_names %in% common_keywords) %>%
  group_by(month, keyword_names) %>%
  count()


keyword_grp <- highlight_key(keyword_cts, ~keyword_names)

p <- ggplot(keyword_grp, aes(x=month, 
                             y=n)) +
  geom_line(col="darkgrey") +
  labs(x="Month",
       y="Number of Articles per Keyword/Month",
       title="Changes in Keywords over Time")

gg <- ggplotly(p)

highlight(gg, on="plotly_hover", off = "plotly_deselect", color = "red", persistent=FALSE)
```

